apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: smartops
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: postgres-service
  DB_PORT: "5432"

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: smartops
type: Opaque
stringData:
  JWT_SECRET: "smartops-secret-key-123456smartops-secret-key-123456"
  JWT_EXPIRATION: "86400000"

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: smartops
type: kubernetes.io/dockercfg
data:
  .dockercfg: eyJsb2NhbGhvc3Q6NTAwMCI6eyJhdXRoIjoiIn19
